GET http://localhost:3000/new-notification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YWE5OTk5ODUwMjJmNzg2YjU5OTA5NyIsImlhdCI6MTcyMjU4MTA0Nn0.OUTi-RB5hOFXS4DylSYHOgur2iP-b7RA8l3SwiFZ65w